apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: pvc-busybox
    namespace: default
  spec:
    storageClassName: "nfs-client"
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 1Gi
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: deploy-busybox-nfs
    name: deploy-busybox-nfs
    namespace: default
  spec:
    replicas: 2
    selector:
      matchLabels:
        app: deploy-busybox-nfs
    template:
      metadata:
        labels:
          app: deploy-busybox-nfs
      spec:
        containers:
        - args:
          - /bin/sh
          - -c
          - while true;do sleep 60;date;done
          image: hub.8ops.top/third/busybox:1.28.0
          name: deploy-busybox-nfs
          resources:
            limits:
              cpu: 50m
              memory: 64Mi
            requests:
              cpu: 50m
              memory: 64Mi
          volumeMounts:
          - name: data
            mountPath: /data1/lib/nfs
            subPath: busybox
        volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pvc-busybox
#    volumeClaimTemplates:
#    - metadata:
#        name: data
#      spec:
#        storageClassName: "nfs-client"
#        accessModes:
#        - "ReadWriteMany"
#        resources:
#          requests:
#            storage: 1Gi
kind: List
