apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: dnspod-imroc-clusterissuer
  labels:
    app: ingress-dnspod-imroc-auto
  name: ingress-dnspod-imroc-auto
  namespace: default
spec:
  ingressClassName: external
  rules:
  - host: ingress-dnspod-imroc-auto.nextn.cn
    http:
      paths:
      - backend:
          service:
            name: echoserver
            port:
              number: 8080
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - nextn.cn
    - "*.nextn.cn"
    secretName: tls-nextn.cn-auto
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: ingress-dnspod-imroc-wildcard
  name: ingress-dnspod-imroc-wildcard
  namespace: default
spec:
  ingressClassName: external
  rules:
  - host: ingress-dnspod-imroc-wildcard.nextn.cn
    http:
      paths:
      - backend:
          service:
            name: echoserver
            port:
              number: 8080
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - ingress-dnspod-imroc-wildcard.nextn.cn
    secretName: tls-nextn.cn-wildcard
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-nextn.cn-wildcard
  namespace: default
spec:
  secretName: tls-nextn.cn-wildcard
  issuerRef:
    name: dnspod-imroc-clusterissuer
    kind: ClusterIssuer
    group: cert-manager.io
  privateKey:
    algorithm: RSA
    size: 2048
    rotationPolicy: Always
  subject:
    organizations:
      - 8OPS Technology Co Ltd
    organizationalUnits:
      - IT Department
    countries:
      - CN
    provinces:
      - Shanghai
    localities:
      - Shanghai
  commonName: nextn.cn
  dnsNames:
  - nextn.cn
  - "*.nextn.cn"
