apiVersion: v1
items:
- apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    labels:
      app: haproxy
    name: haproxy
    namespace: kube-server
  spec:
    ingressClassName: external
    rules:
    - host: haproxy.8ops.top
      http:
        paths:
        - backend:
            service:
              name: haproxy
              port:
                number: 9200
          path: /
          pathType: Prefix
    tls:
    - hosts:
      - haproxy.8ops.top
      secretName: tls-8ops.top
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: haproxy
    name: haproxy
    namespace: kube-server
  spec:
    ports:
    - name: tcp
      port: 9200
      protocol: TCP
      targetPort: 9200
    type: ClusterIP
- apiVersion: v1
  kind: Endpoints
  metadata:
    labels:
      app: haproxy
    name: haproxy
    namespace: kube-server
  subsets:
  - addresses:
    - ip: 10.101.11.110
    ports:
    - name: tcp
      port: 9200
      protocol: TCP
kind: List
