apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    annotations:
      pv.kubernetes.io/bound-by-controller: "yes"
    finalizers:
    - kubernetes.io/pv-protection
    labels:
      pvname: pv-prometheus-server
    name: pv-prometheus-server
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 50Gi
    local:
      path: /opt/data/prometheus/server
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - k-kube-lab-08
    persistentVolumeReclaimPolicy: Retain
    storageClassName: prometheus-server
    volumeMode: Filesystem
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    annotations:
      pv.kubernetes.io/bound-by-controller: "yes"
    finalizers:
    - kubernetes.io/pv-protection
    labels:
      pvname: pv-prometheus-alertmanager
    name: pv-prometheus-alertmanager
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 1Gi
    local:
      path: /opt/data/prometheus/alertmanager
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - k-kube-lab-08
    persistentVolumeReclaimPolicy: Retain
    storageClassName: prometheus-alertmanager
    volumeMode: Filesystem
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    annotations:
      pv.kubernetes.io/bound-by-controller: "yes"
    finalizers:
    - kubernetes.io/pv-protection
    labels:
      pvname: pv-prometheus-pushgateway
    name: pv-prometheus-pushgateway
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 1Gi
    local:
      path: /opt/data/prometheus/pushgateway
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - k-kube-lab-08
    persistentVolumeReclaimPolicy: Retain
    storageClassName: prometheus-pushgateway
    volumeMode: Filesystem
kind: List
