apiVersion: v1
items:
- apiVersion: v1
  kind: Endpoints
  metadata:
    name: kube-etcd
    namespace: kube-system
    labels:
      k8s-app: etcd
  subsets:
  - addresses:
    - ip: 10.101.11.240
    - ip: 10.101.11.114
    - ip: 10.101.11.154
    ports:
    - port: 2379
- apiVersion: v1
  kind: Service
  metadata:
    name: kube-etcd
    namespace: kube-system
    labels:
      k8s-app: etcd
      app.kubernetes.io/name: etcd
  spec:
    type: ClusterIP
    clusterIP: None
    ports:
    - name: port
      port: 2379
      protocol: TCP
kind: List
