apiVersion: v1
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: echoserver
      name: echoserver
      namespace: default
    spec:
      replicas: 1
      revisionHistoryLimit: 5
      selector:
        matchLabels:
          app: echoserver
      strategy:
        rollingUpdate:
          maxSurge: 25%
          maxUnavailable: 25%
        type: RollingUpdate
      template:
        metadata:
          labels:
            app: echoserver
        spec:
          containers:
          - image: hub.8ops.top/google_containers/echoserver:1.10.2
            imagePullPolicy: IfNotPresent
            name: echoserver
            ports:
            - containerPort: 8080
              protocol: TCP
            resources:
              limits:
                cpu: 100m
                memory: 128Mi
              requests:
                cpu: 30m
                memory: 32Mi
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: echoserver
      name: echoserver
      namespace: default
    spec:
      ports:
      - port: 8080
        protocol: TCP
        targetPort: 8080
      selector:
        app: echoserver
      sessionAffinity: None
  - apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      annotations:
        nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
        nginx.ingress.kubernetes.io/limit-rps: "100"
        nginx.ingress.kubernetes.io/ssl-redirect: "false"
      labels:
        app: echoserver
      name: echoserver
      namespace: default
    spec:
      rules:
        - host: echoserver.8ops.top
          http:
            paths:
              - backend:
                  service:
                    name: echoserver
                    port:
                      number: 8080
                path: /
                pathType: Prefix
      tls:
        - hosts:
            - echoserver.8ops.top
          secretName: tls-8ops.top
      ingressClassName: external
kind: List
