apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: kafka-ui
    name: kafka-ui
    namespace: elastic-system
  spec:
    replicas: 1
    revisionHistoryLimit: 5
    selector:
      matchLabels:
        app: kafka-ui
    template:
      metadata:
        labels:
          app: kafka-ui
      spec:
        tolerations:
          - key: "node-role.kubernetes.io/prometheus"
            operator: "Exists"
        containers:
        - image: hub.8ops.top/third/kafka-ui:v20230608
          name: kafka-ui
          env:
          - name: TZ
            value: "Asia/Shanghai"
          - name: DYNAMIC_CONFIG_ENABLED
            value: "true"
          ports:
          - containerPort: 8080
            protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 1024Mi
            requests:
              cpu: 500m
              memory: 1024Mi
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: kafka-ui
    name: kafka-ui
    namespace: elastic-system
  spec:
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: kafka-ui
    type: ClusterIP
- apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    labels:
      app: kafka-ui
    name: kafka-ui
    namespace: elastic-system
  spec:
    ingressClassName: external
    rules:
    - host: kafka-ui.8ops.top
      http:
        paths:
        - backend:
            service:
              name: kafka-ui
              port:
                number: 8080
          path: /
          pathType: Prefix
    tls:
    - hosts:
      - kafka-ui.8ops.top
      secretName: tls-8ops.top
kind: List
