apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-abc.org
  namespace: default
spec:
  secretName: tls-abc.org
  issuerRef:
    name: ca-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
  - "abc.org"
  - "www.abc.org"
  - "*.abc.org"
