apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    annotations:
      pv.kubernetes.io/bound-by-controller: "yes"
    finalizers:
    - kubernetes.io/pv-protection
    labels:
      pvname: pv-redis-cluster-01
    name: pv-redis-cluster-01
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 1Gi
    local:
      path: /opt/data/redis/cluster/01
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - k-kube-lab-12
    persistentVolumeReclaimPolicy: Retain
    storageClassName: redis-cluster
    volumeMode: Filesystem
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    annotations:
      pv.kubernetes.io/bound-by-controller: "yes"
    finalizers:
    - kubernetes.io/pv-protection
    labels:
      pvname: pv-redis-cluster-02
    name: pv-redis-cluster-02
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 1Gi
    local:
      path: /opt/data/redis/cluster/02
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - k-kube-lab-12
    persistentVolumeReclaimPolicy: Retain
    storageClassName: redis-cluster
    volumeMode: Filesystem
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    annotations:
      pv.kubernetes.io/bound-by-controller: "yes"
    finalizers:
    - kubernetes.io/pv-protection
    labels:
      pvname: pv-redis-cluster-03
    name: pv-redis-cluster-03
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 1Gi
    local:
      path: /opt/data/redis/cluster/03
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - k-kube-lab-12
    persistentVolumeReclaimPolicy: Retain
    storageClassName: redis-cluster
    volumeMode: Filesystem
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    annotations:
      pv.kubernetes.io/bound-by-controller: "yes"
    finalizers:
    - kubernetes.io/pv-protection
    labels:
      pvname: pv-redis-cluster-04
    name: pv-redis-cluster-04
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 1Gi
    local:
      path: /opt/data/redis/cluster/04
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - k-kube-lab-12
    persistentVolumeReclaimPolicy: Retain
    storageClassName: redis-cluster
    volumeMode: Filesystem
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    annotations:
      pv.kubernetes.io/bound-by-controller: "yes"
    finalizers:
    - kubernetes.io/pv-protection
    labels:
      pvname: pv-redis-cluster-05
    name: pv-redis-cluster-05
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 1Gi
    local:
      path: /opt/data/redis/cluster/05
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - k-kube-lab-12
    persistentVolumeReclaimPolicy: Retain
    storageClassName: redis-cluster
    volumeMode: Filesystem
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    annotations:
      pv.kubernetes.io/bound-by-controller: "yes"
    finalizers:
    - kubernetes.io/pv-protection
    labels:
      pvname: pv-redis-cluster-06
    name: pv-redis-cluster-06
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 1Gi
    local:
      path: /opt/data/redis/cluster/06
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - k-kube-lab-12
    persistentVolumeReclaimPolicy: Retain
    storageClassName: redis-cluster
    volumeMode: Filesystem
kind: List
