apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    annotations:
      pv.kubernetes.io/bound-by-controller: "yes"
    finalizers:
    - kubernetes.io/pv-protection
    labels:
      pvname: pv-jumpserver-server
    name: pv-jumpserver-server
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 250Gi
    local:
      path: /opt/data/jumpserver/server
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - k-kube-lab-12
    persistentVolumeReclaimPolicy: Retain
    storageClassName: jumpserver-server
    volumeMode: Filesystem
kind: List
