apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    annotations:
      pv.kubernetes.io/bound-by-controller: "yes"
    finalizers:
    - kubernetes.io/pv-protection
    labels:
      pvname: pv-elastic-eck-0
    name: pv-elastic-eck-0
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 10Gi
    local:
      path: /opt/data/elastic/0
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - k-kube-lab-08
    persistentVolumeReclaimPolicy: Retain
    storageClassName: elastic-eck
    volumeMode: Filesystem
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    annotations:
      pv.kubernetes.io/bound-by-controller: "yes"
    finalizers:
    - kubernetes.io/pv-protection
    labels:
      pvname: pv-elastic-eck-1
    name: pv-elastic-eck-1
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 10Gi
    local:
      path: /opt/data/elastic/1
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - k-kube-lab-08
    persistentVolumeReclaimPolicy: Retain
    storageClassName: elastic-eck
    volumeMode: Filesystem
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    annotations:
      pv.kubernetes.io/bound-by-controller: "yes"
    finalizers:
    - kubernetes.io/pv-protection
    labels:
      pvname: pv-elastic-eck-2
    name: pv-elastic-eck-2
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 10Gi
    local:
      path: /opt/data/elastic/2
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - k-kube-lab-08
    persistentVolumeReclaimPolicy: Retain
    storageClassName: elastic-eck
    volumeMode: Filesystem
kind: List
